[package]
name = "rusty-shift-planner"
version = "0.1.0"
authors = ["Markus Paasovaara <markus.paasovaara@barona.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
chrono = "0.4.0"
